name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_VM_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Azure VM
        run: |
          ssh azureuser@${{ secrets.AZURE_VM_IP }} << 'EOF'
          cd ~/fastapi-book-project
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi-app
          EOF
